# Generated by Django 4.1.4 on 2023-02-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BookingFormField',
        ),
        migrations.DeleteModel(
            name='BookingPage',
        ),
    ]
