# Generated by Django 4.1.4 on 2023-01-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_appointmentformfield_contactformfield_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Page', 'verbose_name_plural': 'Contact Page'},
        ),
    ]
