# Generated by Django 4.1.4 on 2023-01-13 01:56

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='contact.contactpage'),
        ),
        migrations.DeleteModel(
            name='AppointmentFormField',
        ),
    ]
