# Generated by Django 4.1.4 on 2023-01-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contactformfield_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='appointment_thank_you_text',
        ),
    ]
