# Generated by Django 4.1.4 on 2023-01-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_remove_contactpage_appointment_thank_you_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_page_title',
            field=models.CharField(default='About Page', help_text='This is the Contact Page.', max_length=50, null=True, verbose_name='Contact Page Subtitle'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='page_description',
            field=models.TextField(help_text='Enter any text to describe your page.', max_length=500, null=True, verbose_name='Page Description'),
        ),
    ]
