# Generated by Django 4.1.4 on 2023-01-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_bookingpage_bookingformfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingpage',
            old_name='contact_thank_you_text',
            new_name='book_thank_you_text',
        ),
    ]
