# Generated by Django 4.1.4 on 2023-01-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_rename_contact_thank_you_text_bookingpage_book_thank_you_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpage',
            name='book_page_title',
            field=models.CharField(default='Booking Page', help_text='This is the Contact Page.', max_length=50, null=True, verbose_name='Booking Page Subtitle'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_page_title',
            field=models.CharField(default='Contact Page', help_text='This is the Contact Page.', max_length=50, null=True, verbose_name='Contact Page Subtitle'),
        ),
    ]
