# Generated by Django 4.1.4 on 2023-02-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_bookingpage_book_page_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpage',
            name='book_page_title',
        ),
        migrations.RemoveField(
            model_name='bookingpage',
            name='page_description',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='contact_page_title',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='page_description',
        ),
    ]
