# Generated by Django 4.1.4 on 2023-02-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_remove_bookingpage_book_page_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='date',
        ),
    ]
