# Generated by Django 4.1.4 on 2023-02-05 14:50

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_remove_bookingpage_date_remove_contactpage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='contact_thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, default="Thank you for contacting us! We'll get back to you shortly."),
        ),
    ]
