# Generated by Django 4.1.4 on 2023-02-10 10:52

import banner.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0078_referenceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(help_text="Enter any title of the banner. Ex. Event's page banner.", max_length=50, null=True, verbose_name='Banner Subtitle')),
                ('description', models.TextField(help_text='Enter any text to describe your banner.', max_length=500, null=True, verbose_name='Page Description')),
                ('video', models.FileField(blank=True, help_text='Upload a video.', max_length=50, null=True, upload_to='banner_videos', validators=[banner.validators.mp4_validate_file_extension], verbose_name='Video Banner')),
                ('url', models.CharField(blank=True, help_text='Ex: https://youtube.com/embed/abc123', max_length=200, null=True, verbose_name='Embed Video Link')),
                ('option', models.CharField(choices=[('show image', 'show image'), ('stream uploaded video', 'stream uploaded video'), ('stream youtube link', 'stream youtube link')], default='show image', help_text='Select which one to showcase', max_length=200, null=True, verbose_name='Settings')),
                ('type', models.CharField(choices=[('home page', 'home page'), ('about page', 'about page'), ('contact page', 'contact page'), ('blog page', 'blog page'), ("event's page", "event's page"), ('products and services page', 'products and services page'), ('talents page', 'talents page')], default='home page', help_text='Select a banner page type', max_length=200, null=True, verbose_name='Type')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'The Banner',
                'verbose_name_plural': 'The Banners',
            },
            bases=('wagtailcore.page',),
        ),
    ]
