# Generated by Django 4.1.4 on 2023-01-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='option',
            field=models.CharField(choices=[('show image', 'show image'), ('stream uploaded video', 'stream uploaded video'), ('stream youtube link', 'stream youtube link')], default='stream image', help_text='select which one to showcase', max_length=200, null=True, verbose_name='Stream Settings'),
        ),
    ]
