# Generated by Django 4.1.4 on 2023-01-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_alter_banners_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpage',
            name='page_desc',
            field=models.CharField(help_text='Enter any text.', max_length=500, null=True, verbose_name='Page Description'),
        ),
    ]
