# Generated by Django 4.1.4 on 2023-01-14 10:33

import banner.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('banner', '0005_alter_banners_options_alter_banners_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerpage',
            name='page_desc',
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='banner_title',
            field=models.TextField(help_text="Enter any title of the banner. Ex. Event's page banner.", max_length=50, null=True, verbose_name='Banner Subtitle'),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='description',
            field=models.TextField(help_text='Enter any text to describe your banner.', max_length=500, null=True, verbose_name='Page Description'),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='option',
            field=models.CharField(choices=[('show image', 'show image'), ('stream uploaded video', 'stream uploaded video'), ('stream youtube link', 'stream youtube link')], default='show image', help_text='Select which one to showcase', max_length=200, null=True, verbose_name='Settings'),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='url',
            field=models.CharField(blank=True, help_text='Ex: https://youtube.com/embed/abc123', max_length=200, null=True, verbose_name='Embed Video Link'),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video.', max_length=50, null=True, upload_to='banner_videos', validators=[banner.validators.mp4_validate_file_extension], verbose_name='Video Banner'),
        ),
        migrations.DeleteModel(
            name='Banners',
        ),
    ]
