# Generated by Django 4.1.4 on 2023-01-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_remove_bannerpage_page_desc_bannerpage_banner_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpage',
            name='type',
            field=models.CharField(choices=[('home page', 'home page'), ('about page', 'about page'), ('contact page', 'contact page'), ('blog page', 'blog page'), ("event's page", "event's page"), ('products and services page', 'products and services page'), ('talents page', 'talents page')], default='home page', help_text='Select a banner page type', max_length=200, null=True, verbose_name='Type'),
        ),
    ]
