# Generated by Django 4.1.4 on 2023-01-15 03:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entry', models.CharField(help_text='You are adding a new package. Ex: Wedding Package, Corporate Party and etc.', max_length=200, null=True, verbose_name='Package Entry')),
            ],
            options={
                'verbose_name': 'Package Entry',
                'verbose_name_plural': 'Package Entries',
            },
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('services_page_title', models.CharField(default='About Page', help_text='This is the Services Page.', max_length=50, null=True, verbose_name='Services Page Subtitle')),
                ('page_description', models.TextField(help_text='Enter any text to describe your page.', max_length=500, null=True, verbose_name='Page Description')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicesPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('package_title', models.CharField(help_text='You are adding a new package. Ex: Wedding Package, Corporate Party and etc.', max_length=200, null=True, verbose_name='Package Title')),
                ('description', models.TextField(help_text='You are adding a new package. Ex: Wedding Package, Corporate Party and etc.', max_length=200, null=True, verbose_name='Package Description')),
                ('package_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_entries', to='services.packageentries')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_package', to='services.servicespage')),
            ],
            options={
                'verbose_name': 'Package Information',
                'verbose_name_plural': 'Packages Information',
            },
        ),
    ]
