# Generated by Django 4.1.4 on 2023-02-10 10:52

import banner.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0078_referenceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('packages', wagtail.fields.StreamField([('package_entry', wagtail.blocks.CharBlock(form_classname='title'))], use_json_field=True)),
                ('description', models.TextField(help_text='Define your package.', max_length=200, null=True, verbose_name='Package Description')),
                ('duration', models.IntegerField()),
                ('unit', models.CharField(choices=[('min', 'min'), ('mins', 'mins'), ('hour', 'hour'), ('hours', 'hours'), ('day', 'day'), ('days', 'days'), ('month', 'month'), ('months', 'months'), ('year', 'year'), ('years', 'years')], default='hour', max_length=7, verbose_name='Time Units')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('show_price_start', models.BooleanField(default=False, verbose_name='Show Price Start Tag')),
                ('remarks', models.TextField(help_text='Enter remarks. Ex: Additional services or information.', max_length=150, null=True, verbose_name='Package Remarks')),
                ('service_video', models.FileField(blank=True, help_text='Upload a video.', max_length=50, null=True, upload_to='banner_videos', validators=[banner.validators.mp4_validate_file_extension], verbose_name='Service Supporting Video')),
                ('service_youtube_url', models.CharField(blank=True, help_text='Ex: https://youtube.com/embed/abc123', max_length=200, null=True, verbose_name='Embed Youtube Video Link')),
                ('service_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Service Page',
                'verbose_name_plural': 'Service Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
