# Generated by Django 4.1.4 on 2023-02-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespage',
            name='description',
            field=models.TextField(blank=True, help_text='Define your package.', max_length=200, null=True, verbose_name='Package Description'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='duration',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enter remarks. Ex: Additional services or information.', max_length=150, null=True, verbose_name='Package Remarks'),
        ),
    ]
