# Generated by Django 4.1.4 on 2023-01-16 15:45

import banner.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicespage',
            options={'verbose_name': 'Service Page', 'verbose_name_plural': 'Services Page'},
        ),
        migrations.RemoveField(
            model_name='servicespackage',
            name='package_entry',
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_video',
            field=models.FileField(blank=True, help_text='Upload a video.', max_length=50, null=True, upload_to='banner_videos', validators=[banner.validators.mp4_validate_file_extension], verbose_name='Service Supporting Video'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_youtube_url',
            field=models.CharField(blank=True, help_text='Ex: https://youtube.com/embed/abc123', max_length=200, null=True, verbose_name='Embed Youtube Video Link'),
        ),
        migrations.AlterField(
            model_name='servicespackage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_packages', to='services.servicespage'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='services_page_title',
            field=models.CharField(help_text='This is the Services Page. Add new service that you offered.', max_length=50, null=True, verbose_name='Services Page Subtitle'),
        ),
        migrations.DeleteModel(
            name='PackageEntries',
        ),
    ]
