# Generated by Django 4.1.4 on 2023-01-16 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('services', '0002_alter_servicespage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='service_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='page_description',
            field=models.TextField(help_text='Enter any text to describe your service.', max_length=500, null=True, verbose_name='Page Description'),
        ),
    ]
