# Generated by Django 4.1.4 on 2023-01-16 16:17

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicespage_service_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespackage',
            name='package_content',
            field=wagtail.fields.StreamField([('package_entry', wagtail.blocks.CharBlock(form_classname='title'))], default=1, use_json_field=True),
            preserve_default=False,
        ),
    ]
