# Generated by Django 4.1.4 on 2023-01-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicespackage_package_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespackage',
            name='description',
            field=models.TextField(help_text='You are adding a new package. Ex: Wedding Packages and Corporate Party Packages to support this service.', max_length=200, null=True, verbose_name='Package Description'),
        ),
    ]
