# Generated by Django 4.1.4 on 2023-01-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicespackage_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicespage',
            old_name='service_image',
            new_name='service_profile_image',
        ),
    ]
