# Generated by Django 4.1.4 on 2023-02-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_servicepage_rename_servicespage_servicedetailpage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedetailpage',
            options={'verbose_name': 'All Services Offered', 'verbose_name_plural': 'All Services Offered'},
        ),
    ]
