# Generated by Django 4.1.4 on 2023-02-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_servicedetailpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetailpage',
            name='unit',
            field=models.CharField(blank=True, choices=[('min', 'min'), ("m's", 'mins'), ('hr', 'hour'), ("hr's", 'hours'), ('d', 'day'), ("d's", 'days'), ('m', 'month'), ('mos', 'months'), ('yr', 'year'), ("yr's", 'years')], default='hour', max_length=7, null=True, verbose_name='Time Units'),
        ),
    ]
