# Generated by Django 4.1.4 on 2023-02-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_servicedetailpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetailpage',
            name='description',
            field=models.TextField(blank=True, help_text='Define your package.', max_length=700, null=True, verbose_name='Package Description'),
        ),
    ]
