# Generated by Django 4.1.4 on 2023-02-12 08:40

import banner.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_servicedetailpage_service_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetailpage',
            name='service_video',
            field=models.FileField(blank=True, help_text='Upload a video.', max_length=50, null=True, upload_to='service_videos', validators=[banner.validators.mp4_validate_file_extension], verbose_name='Service Supporting Video'),
        ),
    ]
