# Generated by Django 4.1.4 on 2022-12-28 14:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('details', wagtail.fields.RichTextField(help_text='Enter your company narrative details.', max_length=1000, verbose_name='Company Details')),
            ],
            options={
                'verbose_name': 'ABOUT US',
                'verbose_name_plural': 'ABOUT US',
            },
            bases=('wagtailcore.page',),
        ),
    ]
