# Generated by Django 4.1.4 on 2023-02-10 10:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0078_referenceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('details', wagtail.fields.RichTextField(blank=True, help_text='Enter your company narrative details.', max_length=1000, verbose_name='Company Details')),
                ('cover_photo', models.ForeignKey(blank=True, help_text='Background image. Best size for this image will be 1400x500', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'About Us Page',
                'verbose_name_plural': 'About Us Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('value', models.PositiveSmallIntegerField(help_text='Enter the whole number value 1-100+', null=True, verbose_name='Analytic Value')),
                ('field', models.CharField(help_text='Enter the field name. ex: "Number of clients".', max_length=40, null=True, verbose_name='Field Name')),
            ],
            options={
                'verbose_name': 'Analytic Entry Page',
                'verbose_name_plural': 'Analytic Entry Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(help_text='Ex: CEO, Manager, Graphic Designer and etc.', max_length=255, null=True, verbose_name='Staff or Employee Role Name')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.TextField(help_text='Please enter your reasons.', null=True, verbose_name='Enter your reason')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_us', to='about.aboutpage')),
            ],
            options={
                'verbose_name': 'WHY CHOOSE US?',
                'verbose_name_plural': 'WHY CHOOSE US?',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(help_text="Enter the client's business name.", max_length=50, null=True, verbose_name='Your name')),
                ('testimony', models.TextField(help_text='Input your narrative speech.', max_length=2000, null=True, verbose_name='Testimony')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PeoplePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.TextField(help_text='Please enter your reasons.', null=True, verbose_name='Enter Employee/Staff Name')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.companyrole')),
            ],
            options={
                'verbose_name': 'Staff and Employee',
                'verbose_name_plural': "Staff's and Employees",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(help_text="Enter the client's business name.", max_length=50, null=True, verbose_name="Client's Name")),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AnalyticSettings',
            fields=[
                ('analytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.analytics')),
                ('analytics_background_img', models.ForeignKey(blank=True, help_text='Background image. Best size for this image will be 1400x400', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Analytic Setup Page',
                'verbose_name_plural': 'Analytics Setup Page',
            },
            bases=('about.analytics',),
        ),
    ]
