# Generated by Django 4.1.4 on 2023-01-04 15:25

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('details', wagtail.fields.RichTextField(blank=True, help_text='Enter your company narrative details.', max_length=1000, verbose_name='Company Details')),
            ],
            options={
                'verbose_name': 'ABOUT US',
                'verbose_name_plural': 'ABOUT US',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('value', models.PositiveSmallIntegerField(help_text='Enter the whole number value 1-100+', null=True, verbose_name='Analytic Value')),
                ('field', models.CharField(help_text='Enter the field name. ex: "Number of clients".', max_length=40, null=True, verbose_name='Field Name')),
            ],
            options={
                'verbose_name': 'Analytic',
                'verbose_name_plural': 'Analytics',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.TextField(help_text='Please enter your reasons.', null=True, verbose_name='Why Choose Us?')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_us', to='about.aboutpage')),
            ],
            options={
                'verbose_name': 'WHY CHOOSE US?',
                'verbose_name_plural': 'WHY CHOOSE US?',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(help_text="Enter the client's business name.", max_length=50, null=True, verbose_name='Your name')),
                ('testimony', wagtail.fields.RichTextField(help_text='Input your narrative speech.', max_length=2000, null=True, verbose_name='Testimony')),
                ('profile_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(help_text="Enter the client's business name.", max_length=50, null=True, verbose_name="Client's Name")),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_img', to='about.aboutpage')),
            ],
            options={
                'verbose_name': 'Featured Image',
                'verbose_name_plural': 'Featured Images',
            },
        ),
    ]
