# Generated by Django 4.1.4 on 2022-12-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(help_text="Enter the client's business name.", max_length=50, null=True, verbose_name="Client's Name"),
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(help_text="Enter the client's business name.", max_length=50, null=True, verbose_name='Your name')),
                ('testimony', models.CharField(help_text='Input your narrative speech.', max_length=2000, null=True, verbose_name='Testimony')),
                ('profile_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
            bases=('wagtailcore.page',),
        ),
    ]
