# Generated by Django 4.1.4 on 2022-12-28 15:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.TextField(help_text='Please enter your reasons.', null=True, verbose_name='Why Choose Us?')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_us', to='about.aboutpage')),
            ],
            options={
                'verbose_name': 'WHY CHOOSE US?',
                'verbose_name_plural': 'WHY CHOOSE US?',
            },
        ),
    ]
