# Generated by Django 4.1.4 on 2023-01-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='address',
            field=models.CharField(help_text='Please enter your company address.', max_length=300, null=True, verbose_name='Company Address'),
        ),
    ]
