# Generated by Django 4.1.4 on 2023-02-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_peoplepage_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplepage',
            name='details',
            field=models.TextField(help_text="Please person's best description.", null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='peoplepage',
            name='name',
            field=models.CharField(help_text='Type the name of the person.', max_length=50, null=True, verbose_name='Employee/Staff Name'),
        ),
    ]
