# Generated by Django 4.1.4 on 2022-12-30 12:46

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_clients_name_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='testimony',
            field=wagtail.fields.RichTextField(help_text='Input your narrative speech.', max_length=2000, null=True, verbose_name='Testimony'),
        ),
    ]
