# Generated by Django 4.1.4 on 2022-12-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutusimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField(help_text='Enter the whole number value 1-100+', null=True, verbose_name='Analytic Value')),
                ('field', models.CharField(help_text='Enter the field name. ex: "Number of clients".', max_length=40, null=True, verbose_name='Field Name')),
            ],
            options={
                'verbose_name': 'Analytic',
                'verbose_name_plural': 'Analytics',
            },
        ),
    ]
