# Generated by Django 4.1.4 on 2023-01-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutpage_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='address',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='city',
            field=models.CharField(help_text="Please enter your company's city location.", max_length=100, null=True, verbose_name='City'),
        ),
    ]
