# Generated by Django 4.1.4 on 2023-02-13 04:16

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_peoplepage_details_alter_peoplepage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplepage',
            name='details',
            field=wagtail.fields.RichTextField(help_text="Please person's best description.", null=True, verbose_name='Details'),
        ),
    ]
