# Generated by Django 4.1.4 on 2023-01-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_aboutpage_address_aboutpage_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychooseus',
            name='text',
            field=models.TextField(help_text='Please enter your reasons.', null=True, verbose_name='Enter your reason'),
        ),
    ]
