# Generated by Django 4.1.4 on 2022-12-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_analytics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='percentage',
            new_name='count',
        ),
    ]
