# Generated by Django 4.1.4 on 2023-01-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_whychooseus_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='house',
            field=models.CharField(help_text='Please enter your building or house number.', max_length=300, null=True, verbose_name='Building/House #'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='street',
            field=models.CharField(help_text="Please enter your company's street location and barangay.", max_length=300, null=True, verbose_name='Street and Barangay'),
        ),
    ]
