# Generated by Django 4.1.4 on 2022-12-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_rename_percentage_analytics_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='count',
            new_name='value',
        ),
    ]
