# Generated by Django 4.1.4 on 2023-01-13 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_aboutpage_house_aboutpage_street'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About us', 'verbose_name_plural': 'About us'},
        ),
    ]
