# Generated by Django 4.1.4 on 2022-12-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutusimage',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='img',
            new_name='image',
        ),
    ]
