# Generated by Django 4.1.4 on 2023-01-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_aboutpage_options_aboutpage_about_page_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='testimony',
            field=models.TextField(help_text='Input your narrative speech.', max_length=2000, null=True, verbose_name='Testimony'),
        ),
    ]
