# Generated by Django 4.1.4 on 2023-01-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_testimonials_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='page_description',
            field=models.TextField(help_text='Enter any text to describe your page.', max_length=500, null=True, verbose_name='Page Description'),
        ),
    ]
