# Generated by Django 4.1.4 on 2023-01-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('about', '0010_alter_aboutpage_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='company_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
