# Generated by Django 4.1.4 on 2023-01-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_aboutpage_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='company_name',
            field=models.CharField(default='Company Name', help_text='Enter company name.', max_length=50, null=True, verbose_name='Company Name'),
        ),
    ]
