# Generated by Django 4.1.4 on 2023-01-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_aboutpage_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='company_name',
        ),
    ]
