# Generated by Django 4.1.4 on 2023-02-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_remove_aboutpage_company_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='date',
        ),
    ]
