# Generated by Django 4.1.4 on 2023-02-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('about', '0014_remove_analytics_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('analytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.analytics')),
                ('analytics_background_img', models.ForeignKey(blank=True, help_text='Background image. Best size for this image will be 1400x400', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Analytic Setup Page',
                'verbose_name_plural': 'Analytics Setup Page',
            },
            bases=('about.analytics',),
        ),
    ]
