# Generated by Django 4.1.4 on 2023-02-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_rename_analyticssettings_analyticsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsettings',
            options={'verbose_name': 'Analytic', 'verbose_name_plural': 'Analytics'},
        ),
    ]
