# Generated by Django 4.1.4 on 2023-02-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_alter_analytics_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='field',
            field=models.CharField(help_text='Enter the field name. ex: "Number of clients".', max_length=40, null=True, verbose_name='Field Name'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='value',
            field=models.PositiveSmallIntegerField(help_text='Enter the whole number value 1-100+', null=True, verbose_name='Analytic Value'),
        ),
    ]
