# Generated by Django 4.1.4 on 2023-02-05 14:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('about', '0019_alter_analytics_field_alter_analytics_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.TextField(help_text='Please enter your reasons.', null=True, verbose_name='Enter Employee/Staff Name')),
            ],
            options={
                'verbose_name': 'People and Position',
                'verbose_name_plural': 'People and Position',
            },
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='city',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='house',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='page_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='street',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.DeleteModel(
            name='AboutUsImage',
        ),
        migrations.AddField(
            model_name='people',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_img', to='about.aboutpage'),
        ),
        migrations.AddField(
            model_name='people',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='people',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.companyrole'),
        ),
    ]
