# Generated by Django 4.1.4 on 2023-02-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_companyrole_people_remove_aboutpage_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='about_page_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='date',
        ),
    ]
