# Generated by Django 4.1.4 on 2023-02-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('about', '0021_remove_aboutpage_about_page_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='cover_photo',
            field=models.ForeignKey(blank=True, help_text='Background image. Best size for this image will be 1400x500', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image'),
        ),
    ]
