# Generated by Django 4.1.4 on 2023-02-09 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('about', '0022_alter_aboutpage_cover_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Staff and Employee', 'verbose_name_plural': "Staff's and Employees"},
        ),
        migrations.RemoveField(
            model_name='people',
            name='id',
        ),
        migrations.RemoveField(
            model_name='people',
            name='page',
        ),
        migrations.RemoveField(
            model_name='people',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='people',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.TextField(default='staff name', help_text='Please enter your reasons.', null=True, verbose_name='Enter Employee/Staff Name'),
        ),
    ]
