# Generated by Django 4.1.4 on 2023-02-09 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0023_alter_people_options_remove_people_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrole',
            name='role_name',
            field=models.CharField(help_text='Ex: CEO, Manager, Graphic Designer and etc.', max_length=255, null=True, verbose_name='Staff or Employee Role Name'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.TextField(help_text='Please enter your reasons.', null=True, verbose_name='Enter Employee/Staff Name'),
        ),
        migrations.AlterField(
            model_name='people',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.companyrole'),
        ),
    ]
