# Generated by Django 4.1.4 on 2023-02-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('about', '0024_alter_companyrole_role_name_alter_people_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='PeoplePage',
        ),
    ]
