# Generated by Django 4.1.4 on 2023-02-10 10:52

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0078_referenceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('company_name', models.CharField(default='No Company Name', help_text='Enter company name.', max_length=50, null=True, verbose_name='Company Name')),
                ('detail', wagtail.fields.RichTextField(help_text='What is your company?', max_length=500, null=True, verbose_name='Company detail')),
                ('address', models.CharField(help_text='Enter your address.', max_length=200, null=True, verbose_name='Address')),
                ('email', models.EmailField(help_text='Enter your email address.', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.PositiveSmallIntegerField(help_text='Enter your mobile phone number.', null=True, verbose_name='Phone number')),
                ('telephone', models.PositiveSmallIntegerField(help_text='Enter your telephone phone number.', null=True, verbose_name='Telephone number')),
                ('bg_color', models.CharField(choices=[('#ffffff', 'light'), ('#3c3c3c', 'dark'), ('#37a1fe', 'blue')], default='#ffffff', max_length=7, verbose_name='Background Color')),
                ('font_color', models.CharField(choices=[('#ffffff', 'light'), ('#3c3c3c', 'dark'), ('#37a1fe', 'blue')], default='#3c3c3c', max_length=7, verbose_name='Font Color')),
                ('company_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Main Setup',
                'verbose_name_plural': 'Main Setup',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_title', models.CharField(blank=True, max_length=50, null=True)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('open_in_new_tab', models.BooleanField(blank=True, default=False)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.menu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
