# Generated by Django 4.1.4 on 2023-02-10 14:17

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default='main-menu', editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(default='Main-Menu', max_length=100),
        ),
    ]
