# Generated by Django 4.1.4 on 2023-01-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('menu', '0002_alter_menu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='company_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='menu',
            name='company_name',
            field=models.CharField(default='Company Name', help_text='Enter company name.', max_length=50, null=True, verbose_name='Company Name'),
        ),
    ]
