# Generated by Django 4.1.4 on 2023-01-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_company_logo_menu_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='company_name',
            field=models.CharField(default='No Company Name', help_text='Enter company name.', max_length=50, null=True, verbose_name='Company Name'),
        ),
    ]
