# Generated by Django 4.1.4 on 2023-01-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('menu', '0004_alter_menu_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='link_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
