# Generated by Django 4.1.4 on 2023-01-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_link_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='link_logo',
            new_name='link_icon',
        ),
    ]
