# Generated by Django 4.1.4 on 2023-02-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_rename_link_logo_menuitem_link_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='address',
            field=models.CharField(help_text='Enter your address.', max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='menu',
            name='detail',
            field=models.CharField(help_text='What is your company?', max_length=500, null=True, verbose_name='Company detail'),
        ),
        migrations.AddField(
            model_name='menu',
            name='email',
            field=models.EmailField(help_text='Enter your email address.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='menu',
            name='phone',
            field=models.PositiveSmallIntegerField(help_text='Enter your telephone phone number.', max_length=11, null=True, verbose_name='Telephone number'),
        ),
    ]
