# Generated by Django 4.1.4 on 2023-02-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menu_address_menu_detail_menu_email_menu_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='telephone',
            field=models.PositiveSmallIntegerField(help_text='Enter your telephone phone number.', max_length=11, null=True, verbose_name='Telephone number'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='phone',
            field=models.PositiveSmallIntegerField(help_text='Enter your mobile phone number.', max_length=11, null=True, verbose_name='Phone number'),
        ),
    ]
