# Generated by Django 4.1.4 on 2023-02-01 20:09

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menu_telephone_alter_menu_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='detail',
            field=wagtail.fields.RichTextField(help_text='What is your company?', max_length=500, null=True, verbose_name='Company detail'),
        ),
    ]
