# Generated by Django 4.1.4 on 2023-02-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menu_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='phone',
            field=models.PositiveSmallIntegerField(help_text='Enter your mobile phone number.', null=True, verbose_name='Phone number'),
        ),
    ]
