# Generated by Django 4.1.4 on 2023-02-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_menu_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='telephone',
            field=models.PositiveSmallIntegerField(help_text='Enter your telephone phone number.', null=True, verbose_name='Telephone number'),
        ),
    ]
