# Generated by Django 4.1.4 on 2023-02-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_menu_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='bg_color_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='bg_gradiant_image',
            field=models.CharField(choices=[('linear-gradient(135deg, #C33764 10%, #1D2671 100%)', 'Dark Purple Blue')], default='linear-gradient(135deg, #C33764 10%, #1D2671 100%)', max_length=50, verbose_name='Background Gradiant Color'),
        ),
    ]
