# Generated by Django 4.1.4 on 2023-02-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_remove_menuitem_link_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Main Setup', 'verbose_name_plural': 'Main Setup'},
        ),
        migrations.AddField(
            model_name='menu',
            name='bg_color',
            field=models.CharField(choices=[('#ffffff', 'light'), ('#3c3c3c', 'dark')], default='light', max_length=7, verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='menu',
            name='font_color',
            field=models.CharField(choices=[('#ffffff', 'light'), ('#3c3c3c', 'dark')], default='dark', max_length=7, verbose_name='Font Color'),
        ),
    ]
