# Generated by Django 4.1.4 on 2023-02-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alter_menu_options_menu_bg_color_menu_font_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='bg_color',
            field=models.CharField(choices=[('#ffffff', 'light'), ('#3c3c3c', 'dark')], default='#ffffff', max_length=7, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='font_color',
            field=models.CharField(choices=[('#ffffff', 'light'), ('#3c3c3c', 'dark')], default='#3c3c3c', max_length=7, verbose_name='Font Color'),
        ),
    ]
