# Generated by Django 4.1.4 on 2023-02-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_menu_bg_color_settings_menu_bg_gradiant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='bg_color_settings',
            field=models.BooleanField(default=False, verbose_name='Use Gradient as Background'),
        ),
    ]
