# Generated by Django 4.1.4 on 2023-02-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_menu_bg_color_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='bg_color',
            field=models.CharField(choices=[('#ffffff', 'Light'), ('#007bff', 'Blue'), ('#37a1fe', 'Sky Blue'), ('#4caf50', 'Green'), ('#7f00ff', 'Purple'), ('#3c3c3c', 'Dark'), ('#000000', 'Black')], default='#ffffff', max_length=7, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='bg_gradiant_image',
            field=models.CharField(choices=[('linear-gradient(135deg, #C33764 10%, #1D2671 100%)', 'Dark Purple Blue'), ('linear-gradient(135deg, #dfe9f3 10%, #ffffff 100%)', 'Light'), ('linear-gradient(135deg, #536976 10%, #292E49 100%)', 'Light Dark'), ('linear-gradient(135deg, #FFDB01 10%, #0E197D 100%)', 'Gold Blue'), ('linear-gradient(135deg, #FF9D6C 10%, #BB4E75 100%)', 'BRT Orange & Mod Pink'), ('linear-gradient(135deg, #007adf 10%, #00ecbc 100%)', 'Dark Sky Blue')], default='linear-gradient(135deg, #C33764 10%, #1D2671 100%)', max_length=50, verbose_name='Background Gradiant Color'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='font_color',
            field=models.CharField(choices=[('#ffffff', 'Light'), ('#007bff', 'Blue'), ('#37a1fe', 'Sky Blue'), ('#4caf50', 'Green'), ('#7f00ff', 'Purple'), ('#3c3c3c', 'Dark'), ('#000000', 'Black')], default='#3c3c3c', max_length=7, verbose_name='Font Color'),
        ),
    ]
