# Generated by Django 4.1.4 on 2023-02-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_alter_menu_bg_color_alter_menu_bg_gradiant_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='bg_gradiant_image',
            field=models.CharField(choices=[('linear-gradient(135deg, #C33764 10%, #1D2671 100%)', 'Dark Purple Blue'), ('linear-gradient(135deg, #dfe9f3 10%, #ffffff 100%)', 'Light'), ('linear-gradient(135deg, #536976 10%, #292E49 100%)', 'Light Dark'), ('linear-gradient(135deg, #FFDB01 10%, #0E197D 100%)', 'Gold Blue'), ('linear-gradient(135deg, #FF9D6C 10%, #BB4E75 100%)', 'BRT Orange & Mod Pink'), ('linear-gradient(135deg, #007adf 10%, #00ecbc 100%)', 'Dark Sky Blue'), ('linear-gradient(135deg, #434343 10%, #000000 100%)', 'Dark Grey')], default='linear-gradient(135deg, #C33764 10%, #1D2671 100%)', max_length=50, verbose_name='Background Gradiant Color'),
        ),
    ]
