# Generated by Django 4.1.4 on 2023-02-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_alter_menu_bg_gradiant_image_alter_menu_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='font_color',
            field=models.CharField(choices=[('#ffffff', 'Light'), ('#007bff', 'Blue'), ('#37a1fe', 'Sky Blue'), ('#4caf50', 'Green'), ('#7f00ff', 'Purple'), ('#3c3c3c', 'Dark'), ('#000000', 'Black')], default='#ffffff', max_length=7, verbose_name='Font Color'),
        ),
    ]
