# Generated by Django 4.1.4 on 2023-02-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpage',
            name='booking_cover_settings',
            field=models.BooleanField(default=True, help_text='Do you want to use the default parallax cover image? click the box for yes.', verbose_name='Use Default Background Image'),
        ),
        migrations.AddField(
            model_name='bookingpage',
            name='booking_page_background',
            field=models.ForeignKey(blank=True, help_text='Best size will be 1920x1080 pixels.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
